package httpapi_test

import (
	"context"
	"encoding/json"
	"errors"
	"net/http"
	"testing"
	"time"

	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/authn/capability"
	authpolicy "github.com/a05p6mk01p3/EnrollmentPlatform/internal/authn/policy"
	authruntime "github.com/a05p6mk01p3/EnrollmentPlatform/internal/authn/runtime"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/config"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/generated/openapi"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/httpapi"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/idempotency/runtime"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/partnerauth"
	preonboardingapp "github.com/a05p6mk01p3/EnrollmentPlatform/internal/preonboarding/application"
	domain "github.com/a05p6mk01p3/EnrollmentPlatform/internal/preonboarding/domain"
	preonboardingruntime "github.com/a05p6mk01p3/EnrollmentPlatform/internal/preonboarding/runtime"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/replaycapsule"
	"github.com/a05p6mk01p3/EnrollmentPlatform/internal/resourceownership"
	"sync"
)

type countedToken struct {
	calls int
}

func (g *countedToken) NewRequestAccessToken(context.Context) (string, error) {
	g.calls++
	return "m56-integration-token-plaintext", nil
}

type faultyProtector struct {
	failSeal bool
	openErr  error
	opens    int // counts Open invocations (replay recovery boundary)
	real     runtime.Protector
}

func (f *faultyProtector) Seal(ctx context.Context, p []byte, a []byte) (*runtime.ProtectedEnvelope, error) {
	if f.failSeal {
		return nil, runtime.ErrUnusableProtector
	}
	return f.real.Seal(ctx, p, a)
}

func (f *faultyProtector) Open(ctx context.Context, e *runtime.ProtectedEnvelope, a []byte) ([]byte, error) {
	f.opens++
	if f.openErr != nil {
		return nil, f.openErr
	}
	return f.real.Open(ctx, e, a)
}

type faultyUoW struct {
	real preonboardingapp.UnitOfWork
	fail bool
}

func (f *faultyUoW) Repository() preonboardingapp.Repository   { return f.real.Repository() }
func (f *faultyUoW) ResultStore() preonboardingapp.ResultStore { return f.real.ResultStore() }
func (f *faultyUoW) AuditWriter() preonboardingapp.AuditWriter { return f.real.AuditWriter() }
func (f *faultyUoW) IdempotencyStore() runtime.Store           { return f.real.IdempotencyStore() }
func (f *faultyUoW) RequestAccessWriter() preonboardingapp.RequestAccessWriter {
	return f.real.RequestAccessWriter()
}
func (f *faultyUoW) TemporaryPrincipalStore() preonboardingapp.TemporaryPrincipalStore {
	return f.real.TemporaryPrincipalStore()
}
func (f *faultyUoW) Commit(ctx context.Context) error {
	if f.fail {
		f.real.Rollback(ctx)
		return errors.New("injected outer UoW commit failure")
	}
	return f.real.Commit(ctx)
}
func (f *faultyUoW) Rollback(ctx context.Context) error { return f.real.Rollback(ctx) }

type faultyUoWManager struct {
	real       preonboardingapp.UnitOfWorkManager
	failCommit bool
	onBegin    func(preonboardingapp.UnitOfWork) preonboardingapp.UnitOfWork
}

func (f *faultyUoWManager) Begin(ctx context.Context) (preonboardingapp.UnitOfWork, error) {
	uow, err := f.real.Begin(ctx)
	if err != nil {
		return nil, err
	}
	if f.onBegin != nil {
		return f.onBegin(uow), nil
	}
	return &faultyUoW{real: uow, fail: f.failCommit}, nil
}

type m56HTTPFixture struct {
	store          *preonboardingruntime.MemoryStore
	recorder       *preonboardingruntime.MemoryAuditRecorder
	clock          *preonboardingruntime.MockClock
	partnerAuth    *preonboardingruntime.MemoryPartnerAuthorityChecker
	partnerElig    *preonboardingruntime.MemoryPartnerEligibilityChecker
	tokens         *countedToken
	handler        http.Handler
	protector      *faultyProtector
	uowManagerMock *faultyUoWManager
	verifierKey    capability.VerifierKey
	verifier       capability.Verifier
}

func newM56HTTPFixture(t *testing.T, initialTime time.Time) *m56HTTPFixture {
	t.Helper()

	recorder := preonboardingruntime.NewMemoryAuditRecorder()
	store := preonboardingruntime.NewMemoryStore(recorder)
	clock := preonboardingruntime.NewMockClock(initialTime)
	partnerAuth := preonboardingruntime.NewMemoryPartnerAuthorityChecker()
	partnerElig := preonboardingruntime.NewMemoryPartnerEligibilityChecker()

	// Grant partner authority for the principal generated by tokHuman
	// (Issuer: "test-issuer", Subject: "test-subject-human")
	adminPrincipal := preonboardingapp.AdminPrincipal{
		Issuer:  "test-issuer",
		Subject: "test-subject-human",
	}
	partnerAuth.GrantPartnerAuthority(adminPrincipal, "P1")

	verifier, err := capability.NewHMACVerifier([]byte("capability-verifier-key-m56a-32bytes!"))
	if err != nil {
		t.Fatal(err)
	}

	realProtector, err := replaycapsule.NewAEADProtector([]byte("replay-capsule-protector-key-32!"), "m56a", func() time.Time { return clock.Now().Add(time.Hour) })
	if err != nil {
		t.Fatal(err)
	}
	faultyProt := &faultyProtector{real: realProtector}

	tokens := &countedToken{}
	uowMock := &faultyUoWManager{real: store}

	preonboardSvc, err := preonboardingapp.NewService(preonboardingapp.ServiceConfig{
		UOWManager:                 uowMock,
		Clock:                      clock,
		DeviceAllocator:            preonboardingruntime.DefaultDeviceAllocator{},
		PartnerAuth:                partnerAuth,
		PartnerEligibility:         partnerElig,
		RetentionPolicy:            preonboardingapp.StaticIdempotencyRetentionPolicy{Duration: 24 * time.Hour},
		ReplayCapsulePolicy:        preonboardingapp.StaticReplayCapsuleRetentionPolicy{Duration: time.Hour},
		RequestAccessTokenLifetime: preonboardingapp.StaticRequestAccessTokenLifetime{Duration: 30 * time.Minute},
		Create: &preonboardingapp.CreateDependencies{
			IDGenerator:    preonboardingapp.CryptoIDGenerator{},
			TokenGenerator: tokens,
			Verifier:       verifier,
			Protector:      faultyProt,
		},
	})
	if err != nil {
		t.Fatalf("NewService failed: %v", err)
	}

	cfg := config.Config{GeneralJSONDefaultBytes: 262144, AbsoluteRequestBodyBytes: 4 << 20}

	partnerSvc, err := partnerauth.NewService(
		humanResolver(map[string]partnerauth.HumanAuthorizations{
			"test-subject-human": {
				PrincipalID: "principal-123",
				Partners: []partnerauth.PartnerAuthorization{
					{PartnerID: "P1", DisplayName: "Partner 1", Scopes: []string{"device:preonboard"}},
				},
			},
		}),
		partnerauth.StaticTemporaryPrincipalResolver{
			Resolve: func(ctx context.Context, id partnerauth.TemporaryPrincipalID) (partnerauth.TemporaryPrincipalAuthorization, error) {
				uow, err := store.Begin(ctx)
				if err != nil {
					return partnerauth.TemporaryPrincipalAuthorization{}, err
				}
				defer uow.Rollback(ctx)
				tp, ok, err := uow.TemporaryPrincipalStore().Get(ctx, string(id))
				if err != nil {
					return partnerauth.TemporaryPrincipalAuthorization{}, err
				}
				if !ok {
					return partnerauth.TemporaryPrincipalAuthorization{}, partnerauth.ErrDependencyUnavailable
				}
				exp := tp.ExpiresAt
				var status partnerauth.TemporaryPrincipalStatus = partnerauth.TemporaryPrincipalStatusDisabled
				if tp.Status == domain.TPStatusActive {
					status = partnerauth.TemporaryPrincipalStatusActive
				}
				return partnerauth.TemporaryPrincipalAuthorization{
					TemporaryPrincipalID: tp.TemporaryPrincipalID,
					PartnerID:            string(tp.PartnerID),
					Status:               status,
					ExpiresAt:            &exp,
					Scopes:               []string{"device:preonboard"},
				}, nil
			},
		},
		partnerauth.WithClock(clock.Now),
	)
	if err != nil {
		t.Fatalf("partnerauth.NewService failed: %v", err)
	}
	ownershipSvc, err := resourceownership.NewService(
		resourceownership.StaticPreOnboardingOwnershipResolver{
			Resolve: func(ctx context.Context, id string) (resourceownership.OwnershipResult, error) {
				return resourceownership.OwnershipNotFound(), nil
			},
		},
		partnerSvc,
	)
	if err != nil {
		t.Fatalf("resourceownership.NewService failed: %v", err)
	}

	srv, err := httpapi.NewServer(cfg,
		httpapi.WithAuthnRegistry(matrixRegistry(t)),
		httpapi.WithDeviceMTLSSource(matrixDeviceSource()),
		httpapi.WithAuthzRegistry(testAuthzRegistry()),
		httpapi.WithPartnerAuthService(partnerSvc),
		httpapi.WithResourceOwnershipService(ownershipSvc),
		httpapi.WithPreOnboardingService(preonboardSvc),
	)
	if err != nil {
		t.Fatalf("NewServer failed: %v", err)
	}

	p := &probeSSI{calls: map[string]int{}}
	h := srv.Handler(p)

	return &m56HTTPFixture{
		store:          store,
		recorder:       recorder,
		clock:          clock,
		partnerAuth:    partnerAuth,
		partnerElig:    partnerElig,
		tokens:         tokens,
		handler:        h,
		protector:      faultyProt,
		uowManagerMock: uowMock,
		verifier:       verifier,
	}
}

func TestM56_HumanOIDC_HTTP_NEW_and_REPLAY(t *testing.T) {
	tc := newM56HTTPFixture(t, time.Now())

	reqBody := `{"partner_id":"P1","agent":{"platform":"windows","version":"1.0"},"claimed_device":{"hostname":"node-m56"}}`

	// HTTP NEW
	rr1 := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-human-oidc", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-integration-key-1",
		"X-Correlation-ID": "corr-1",
	})

	if rr1.Code != http.StatusCreated {
		t.Fatalf("expected 201 Created, got %d. Body: %s", rr1.Code, rr1.Body.String())
	}

	var resp1 openapi.PreOnboardingCreateResponse
	if err := json.Unmarshal(rr1.Body.Bytes(), &resp1); err != nil {
		t.Fatal(err)
	}

	if resp1.PreOnboardingRequestId == "" {
		t.Fatal("expected non-empty pre_onboarding_request_id")
	}
	if resp1.Status != openapi.PreOnboardingCreateResponseStatusPENDINGAPPROVAL {
		t.Fatalf("expected PENDING_APPROVAL, got %s", resp1.Status)
	}
	if string(resp1.PartnerId) != "P1" {
		t.Fatalf("expected partner P1, got %s", resp1.PartnerId)
	}
	if resp1.RequestAccessToken != "m56-integration-token-plaintext" {
		t.Fatalf("expected correct plaintext token, got %s", resp1.RequestAccessToken)
	}

	etag1 := rr1.Header().Get("ETag")
	if etag1 == "" {
		t.Fatal("expected non-empty ETag")
	}
	loc1 := rr1.Header().Get("Location")
	if loc1 != "/v1/pre-onboarding-requests/"+string(resp1.PreOnboardingRequestId) {
		t.Fatalf("expected correct Location, got %s", loc1)
	}
	if rr1.Header().Get("X-Correlation-ID") != "corr-1" {
		t.Fatalf("expected corr-1, got %s", rr1.Header().Get("X-Correlation-ID"))
	}

	// Verify Authenticator
	auth := capability.NewRequestAccessAuthenticator(tc.verifier, tc.store, tc.clock)
	gotAuth := auth.Authenticate(context.Background(), &authruntime.Credential{BearerToken: resp1.RequestAccessToken})
	if gotAuth.Decision != authruntime.DecisionAuthenticated {
		t.Fatalf("expected Authenticated, got %v", gotAuth.Decision)
	}
	b, ok := gotAuth.Binding.RequestAccess()
	if !ok || b.PreOnboardingRequestID != string(resp1.PreOnboardingRequestId) {
		t.Fatalf("expected matching binding, got %+v", b)
	}

	// HTTP REPLAY
	rr2 := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-human-oidc", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-integration-key-1",
		"X-Correlation-ID": "corr-2",
	})

	if rr2.Code != http.StatusCreated {
		t.Fatalf("expected 201 Created on replay, got %d. Body: %s", rr2.Code, rr2.Body.String())
	}

	var resp2 openapi.PreOnboardingCreateResponse
	if err := json.Unmarshal(rr2.Body.Bytes(), &resp2); err != nil {
		t.Fatal(err)
	}

	if resp2.PreOnboardingRequestId != resp1.PreOnboardingRequestId {
		t.Fatal("id mismatch on replay")
	}
	if resp2.RequestAccessToken != resp1.RequestAccessToken {
		t.Fatal("token mismatch on replay")
	}
	if rr2.Header().Get("ETag") != etag1 {
		t.Fatal("ETag mismatch on replay")
	}
	if rr2.Header().Get("Location") != loc1 {
		t.Fatal("Location mismatch on replay")
	}
	if rr2.Header().Get("X-Correlation-ID") != "corr-2" {
		t.Fatal("Correlation-ID mismatch on replay")
	}

	if tc.tokens.calls != 1 {
		t.Fatalf("expected exactly 1 token generation, got %d", tc.tokens.calls)
	}
}

func TestM56_SealFailure_Atomicity(t *testing.T) {
	tc := newM56HTTPFixture(t, time.Now())
	tc.protector.failSeal = true

	reqBody := `{"partner_id":"P1","agent":{"platform":"windows","version":"1.0"},"claimed_device":{"hostname":"node-m56"}}`

	rr := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-human-oidc", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-integration-seal",
		"X-Correlation-ID": "corr-seal",
	})

	assertProblem(t, rr, http.StatusServiceUnavailable, "DEPENDENCY_UNAVAILABLE")

	// Verify rollback
	key, _ := tc.verifier.Derive(authpolicy.CredentialKindRequestAccessToken, "m56-integration-token-plaintext")
	if _, err := tc.store.LookupRequestAccess(context.Background(), key); err == nil {
		t.Fatal("verifier leaked on seal failure")
	}
}

func TestM56_OuterCommitFailure_Atomicity(t *testing.T) {
	tc := newM56HTTPFixture(t, time.Now())
	tc.uowManagerMock.failCommit = true

	reqBody := `{"partner_id":"P1","agent":{"platform":"windows","version":"1.0"},"claimed_device":{"hostname":"node-m56"}}`

	rr := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-human-oidc", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-integration-commit",
		"X-Correlation-ID": "corr-commit",
	})

	assertProblem(t, rr, http.StatusServiceUnavailable, "DEPENDENCY_UNAVAILABLE")

	// Verify rollback
	key, _ := tc.verifier.Derive(authpolicy.CredentialKindRequestAccessToken, "m56-integration-token-plaintext")
	if _, err := tc.store.LookupRequestAccess(context.Background(), key); err == nil {
		t.Fatal("verifier leaked on outer commit failure")
	}
}

func TestM56_TP_HTTP_NEW_and_REPLAY_WithZeroQuota(t *testing.T) {
	now := time.Date(2026, 8, 25, 12, 0, 0, 0, time.UTC)
	tc := newM56HTTPFixture(t, now)

	tpID := "test-tp-temporary-principal"
	tp := &domain.TemporaryPrincipal{
		TemporaryPrincipalID: tpID,
		PartnerID:            "P1",
		Status:               domain.TPStatusActive,
		ExpiresAt:            now.Add(time.Hour),
		MaxSubmissions:       1,
		CommittedSubmissions: 0,
	}
	tc.store.SeedTemporaryPrincipal(tp)

	reqBody := `{"partner_id":"P1","agent":{"platform":"windows","version":"1.0"},"claimed_device":{"hostname":"node-m56-tp"}}`

	// 1. HTTP NEW
	rr1 := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-temporary-principal", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-tp-integration-key-1",
		"X-Correlation-ID": "corr-tp-1",
	})

	if rr1.Code != http.StatusCreated {
		t.Fatalf("expected 201 Created, got %d. Body: %s", rr1.Code, rr1.Body.String())
	}

	var resp1 openapi.PreOnboardingCreateResponse
	if err := json.Unmarshal(rr1.Body.Bytes(), &resp1); err != nil {
		t.Fatal(err)
	}

	if resp1.PreOnboardingRequestId == "" {
		t.Fatal("expected non-empty pre_onboarding_request_id")
	}
	if string(resp1.PartnerId) != "P1" {
		t.Fatalf("expected partner P1, got %s", resp1.PartnerId)
	}

	etag1 := rr1.Header().Get("ETag")
	loc1 := rr1.Header().Get("Location")

	// Verify quota is consumed
	uow, _ := tc.store.Begin(context.Background())
	tpRec, _, _ := uow.TemporaryPrincipalStore().Get(context.Background(), tpID)
	uow.Rollback(context.Background())
	if tpRec.CommittedSubmissions != 1 {
		t.Fatalf("expected quota consumed to 1, got %d", tpRec.CommittedSubmissions)
	}

	// 2. HTTP REPLAY with zero remaining quota
	rr2 := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-temporary-principal", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-tp-integration-key-1",
		"X-Correlation-ID": "corr-tp-2",
	})

	if rr2.Code != http.StatusCreated {
		t.Fatalf("expected 201 Created on replay, got %d. Body: %s", rr2.Code, rr2.Body.String())
	}

	var resp2 openapi.PreOnboardingCreateResponse
	if err := json.Unmarshal(rr2.Body.Bytes(), &resp2); err != nil {
		t.Fatal(err)
	}

	if resp2.PreOnboardingRequestId != resp1.PreOnboardingRequestId {
		t.Fatal("id mismatch on replay")
	}
	if resp2.RequestAccessToken != resp1.RequestAccessToken {
		t.Fatal("token mismatch on replay")
	}
	if rr2.Header().Get("ETag") != etag1 {
		t.Fatal("ETag mismatch on replay")
	}
	if rr2.Header().Get("Location") != loc1 {
		t.Fatal("Location mismatch on replay")
	}
	if rr2.Header().Get("X-Correlation-ID") != "corr-tp-2" {
		t.Fatal("Correlation-ID mismatch on replay")
	}

	// Verify quota remains 1
	uow, _ = tc.store.Begin(context.Background())
	tpRec, _, _ = uow.TemporaryPrincipalStore().Get(context.Background(), tpID)
	uow.Rollback(context.Background())
	if tpRec.CommittedSubmissions != 1 {
		t.Fatalf("expected quota to remain 1, got %d", tpRec.CommittedSubmissions)
	}

	// Verify Authenticator works on the returned token
	auth := capability.NewRequestAccessAuthenticator(tc.verifier, tc.store, tc.clock)
	gotAuth := auth.Authenticate(context.Background(), &authruntime.Credential{BearerToken: resp1.RequestAccessToken})
	if gotAuth.Decision != authruntime.DecisionAuthenticated {
		t.Fatalf("expected Authenticated, got %v", gotAuth.Decision)
	}

	// 3. Disable TP and verify replay fails
	tp.Status = domain.TPStatusDisabled
	tc.store.SeedTemporaryPrincipal(tp)

	rr3 := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-temporary-principal", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-tp-integration-key-1",
		"X-Correlation-ID": "corr-tp-3",
	})

	if rr3.Code != http.StatusForbidden {
		t.Fatalf("expected 403 Forbidden on disabled TP, got %d. Body: %s", rr3.Code, rr3.Body.String())
	}
}

type syncUOW struct {
	preonboardingapp.UnitOfWork
	beforeCommit func()
}

func (s *syncUOW) Commit(ctx context.Context) error {
	if s.beforeCommit != nil {
		s.beforeCommit()
	}
	return s.UnitOfWork.Commit(ctx)
}

func TestM56_TP_HTTP_InProgress(t *testing.T) {
	now := time.Date(2026, 8, 25, 12, 0, 0, 0, time.UTC)
	tc := newM56HTTPFixture(t, now)

	tpID := "test-tp-temporary-principal"
	tp := &domain.TemporaryPrincipal{
		TemporaryPrincipalID: tpID,
		PartnerID:            "P1",
		Status:               domain.TPStatusActive,
		ExpiresAt:            now.Add(time.Hour),
		MaxSubmissions:       2,
		CommittedSubmissions: 0,
	}
	tc.store.SeedTemporaryPrincipal(tp)

	reqBody := `{"partner_id":"P1","agent":{"platform":"windows","version":"1.0"},"claimed_device":{"hostname":"node-m56-tp-in-progress"}}`

	blockCommit := make(chan struct{})
	doneCommit := make(chan struct{})
	tc.uowManagerMock.onBegin = func(uow preonboardingapp.UnitOfWork) preonboardingapp.UnitOfWork {
		return &syncUOW{
			UnitOfWork: uow,
			beforeCommit: func() {
				close(doneCommit)
				<-blockCommit
			},
		}
	}

	var wg sync.WaitGroup
	wg.Add(1)
	go func() {
		defer wg.Done()
		doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
			"Authorization": "Bearer tok-temporary-principal", "Content-Type": "application/json",
			"Idempotency-Key":  "m56-tp-in-progress-key",
			"X-Correlation-ID": "corr-tp-ip-1",
		})
	}()

	<-doneCommit

	// Now try another request with the same key while the first is in progress
	rr := doAuth(t, tc.handler, "POST", "/v1/pre-onboarding-requests", reqBody, map[string]string{
		"Authorization": "Bearer tok-temporary-principal", "Content-Type": "application/json",
		"Idempotency-Key":  "m56-tp-in-progress-key",
		"X-Correlation-ID": "corr-tp-ip-2",
	})

	if rr.Code != http.StatusServiceUnavailable {
		t.Fatalf("expected 503 Service Unavailable for in-progress request, got %d", rr.Code)
	}
	assertProblem(t, rr, http.StatusServiceUnavailable, "DEPENDENCY_UNAVAILABLE")

	close(blockCommit)
	wg.Wait()

	// Verify quota is exactly 1 (only the first completed successfully, the second did not execute/increment quota)
	uow, _ := tc.store.Begin(context.Background())
	tpRec, _, _ := uow.TemporaryPrincipalStore().Get(context.Background(), tpID)
	uow.Rollback(context.Background())
	if tpRec.CommittedSubmissions != 1 {
		t.Fatalf("expected CommittedSubmissions to be 1, got %d", tpRec.CommittedSubmissions)
	}
}
