package runtime

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
)

// NewReservationToken generates a fresh opaque, unforgeable reservation token
// for use by a server-side Store adapter. The token grants no authority unless
// the Store atomically returns NEW for it; authority is the Store's ownership
// mapping, never the token's formatting.
func NewReservationToken() (ReservationToken, error) {
	var b [16]byte
	if _, err := rand.Read(b[:]); err != nil {
		return ReservationToken{}, fmt.Errorf("idempotency runtime: generating reservation token: %w", err)
	}
	return ReservationToken{value: hex.EncodeToString(b[:])}, nil
}

// ReservationTokenFromString restores a ReservationToken from an exact opaque
// value previously produced by Value (or generated by NewReservationToken).
// It validates the value (non-empty printable ASCII, no surrounding
// whitespace) and fails closed rather than accepting malformed authority. It
// is an adapter-facing persistence/restore API, not an HTTP/wire format.
func ReservationTokenFromString(value string) (ReservationToken, error) {
	if value == "" {
		return ReservationToken{}, fmt.Errorf("idempotency runtime: reservation token must be non-empty")
	}
	for i := 0; i < len(value); i++ {
		c := value[i]
		if c < 0x21 || c > 0x7E {
			return ReservationToken{}, fmt.Errorf("idempotency runtime: reservation token contains invalid byte 0x%02x at offset %d", c, i)
		}
	}
	return ReservationToken{value: value}, nil
}
